name: flutter_web_template
description: Flutter template project for android, ios and web.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.2

  flutter_localizations:
    sdk: flutter
  intl: any
  intl_utils: ^2.8.5

  # Architecture
  json_annotation: ^4.8.1
  go_router: ^12.0.0
  get_it: ^7.6.4
  injectable: ^2.3.2
  flutter_bloc: ^8.1.3
  bloc_concurrency: ^0.2.2
  equatable: ^2.0.5
  freezed_annotation: ^2.4.1

  logger: ^2.0.2+1
  fluttertoast: ^8.2.2
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  json_serializable: ^6.7.1
  build_runner: any
  flutter_gen_runner: any
  freezed: ^2.4.5
  injectable_generator: ^2.4.1

flutter_intl:
  enabled: true
  class_name: L
  main_locale: vi
  arb_dir: lib/l10n
  output_dir: lib/l10n/generated

flutter_gen:
  output: lib/gen/

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
