name: flutter_template
description: Flutter template project for android, ios and web.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: 3.19.3

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.2

  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  intl_utils: ^2.8.5

  # Architecture
  go_router: ^14.1.0
  get_it: ^7.6.4
  injectable: ^2.3.2
  flutter_bloc: ^8.1.3
  bloc_concurrency: ^0.2.2
  equatable: ^2.0.5

  # Support Freezed
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1

  # UI
  gap: ^3.0.1
  shimmer: ^3.0.0

  # Utility for Dart
  quiver: ^3.2.1
  dartx: ^1.2.0

  # Prints beautiful logs
  logger: ^2.0.2+1
  pretty_dio_logger: ^1.3.1

  # Store data
  flutter_secure_storage: ^9.0.0

  fluttertoast: ^8.2.2

  # Network
  dio: ^5.4.0
  retrofit: ^4.0.3

  # Utility
  connectivity_plus: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.9
  flutter_gen_runner: ^5.4.0
  freezed: ^2.4.5
  injectable_generator: ^2.4.1
  retrofit_generator: ^8.1.0

flutter_intl:
  enabled: true
  class_name: L
  main_locale: vi
  arb_dir: lib/l10n
  output_dir: lib/l10n/generated

flutter_gen:
  output: lib/gen/

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Black.ttf
          weight: 900
        - asset: assets/fonts/roboto/Roboto-BlackItalic.ttf
          weight: 900
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/roboto/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/roboto/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/roboto/Roboto-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/roboto/Roboto-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/roboto/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/roboto/Roboto-ThinItalic.ttf
          weight: 100
          style: italic
